jneem/imbl

src/hash/map.rs, src/hash/set.rs, src/ord/map.rs, src/ord/set.rs
`fn union(self, other: Self) -> Self` is implemented by progressively
mutating then returning one of the two given collections,
while consuming and iterating the other.
If one of the two collections is much larger,
mutating that one can be faster and yield better reuse of internal nodes.
This is #163 in im-rs.
=> Build union of two maps/sets by mutating the larger one, not the first

src/vector/mod.rs
=> Fix documented time complexity for Vector::ptr_eq

src/hash/map.rs
Per the doc, union should keep the values in **the current map** when keys exist in both maps.
It is accidentally broken in #13. This fixes the issue.
=> fix HashMap::union

src/vector/mod.rs
Users frequently want to use a custom ordering for their Vector types. One way to accomplish this is to implement the Ord trait (along with PartialOrd and usually PartialEq/Eq) using the desired custom logic for comparisons.
However, this can lead to a lot of boilerplate code for what is often a small, one-off use case. This has to to the Standard Library, and libraries like imbl that offer similar APIs, creating methods such as sort_by, sort_by_key, etc. that allow a user to pass a comparator function that the library will use to sort or insert into the list.
This PR implements the insert_ord_by and insert_order_by_key methods, providing a way to use a custom comparator function to insert into a sorted list without needing to define the usual Rust comparison traits.
=> add Vector::insert_ord_by[_key] methods

src/lib.rs, src/nodes/btree.rs, src/nodes/hamt.rs, src/util.rs, src/vector/focus.rs, src/vector/mod.rs
This also deletes swap_indices, which is unsound even though it was
neither public nor used in an unsound way.
Fixes #24
=> Removes some of the allow(unsafe_code) boilerplate.

src/vector/focus.rs
This documents some of the internals of the Focus and FocusMut. Each attribute of the Focus/FocusMut is documented including all of their private methods.
=> Adds a collection of information about the Focus and FocusMut internals

src/hash/set.rs
Implement From for arrays to conveniently initialize a set ```[1,2,3].into()```.
Like collections::HashSet does.
=> Implement From array

src/nodes/btree.rs, src/ord/map.rs, src/ord/set.rs
This is a breaking change but only for code that uses turbofish syntax
on the `diff` method, the `DiffIter` type, or the `DiffItem` type.
Adapted from `im` PR #168.
Co-authored-by: Joe Neeman <joeneeman@gmail.com>
=> Separate the lifetimes of each input of OrdMap::diff and OrdSet::diff

.github/workflows/coverage.yml
No people working on this crate should get the rustfmt defaults,
even if they have a different global rustfmt configuration.
=> Add empty rustfmt config.

src/vector/mod.rs
In a previous PR I added an impl from array for HashSet but not for Vector (sorry!). This allows easy initialization like
```
[1,2].into()
```
=> Vector impls From array [A;N]

CHANGELOG.md, Cargo.toml, src/hash/map.rs, src/hash/set.rs, src/ord/map.rs, src/ord/set.rs
Here is a PR as promised in issue #56 
I'd still like to go through the docs, and see if anything else jumps out at me, and wait for feedback from others though.
Edit: The only usages of it are in the doctests for the alias itself afaict.
=> deprecate the `difference` function.

benches/vector.rs, src/hash/map.rs, src/nodes/btree.rs, src/nodes/hamt.rs, src/ord/map.rs, src/ser.rs, src/vector/mod.rs
Automated with `cargo +nightly clippy --fix`. Undid two invalid changes by hand (cc https://github.com/rust-lang/rust-clippy/issues/11341).
=> Fix clippy lints

src/hash/map.rs, src/nodes/hamt.rs
Most importantly, the Debug implementation no longer requires any bounds other than K: Debug and V: Debug, allowing users to derive Debug for structs that are generic over key and/or value of an internal HashMap.
=> hashmap: Remove unnecessary trait bounds

CHANGELOG.md, src/vector/mod.rs
Closes #66. I wanted to make the impl smarter, but `split_off`, which `truncate` currently uses as its implementation, is quite large and I don't understand im(bl)'s internals well enough to make this a quick PR. Will look into adding `InlineArray::truncate` as a first step though.
=> Don't panic in truncate if len > self.len()

CHANGELOG.md, src/ord/set.rs
This PR adds the get function to `OrdSet` so that we can get keys by a borrowed form. This is useful for example when you have a unique identifier for a struct (that is part of the struct) and want to keep these structs in the Set, while accessing them via the identifier only.
See also: https://doc.rust-lang.org/std/collections/struct.BTreeSet.html#method.get
=> feat: Bring OrdSet in line with BTreeSet from std library by adding get.

src/ser.rs
The impls are not really useful for non-`Clone` types, but this allows deriving `Serialize` for types with fields of type `imbl::Container<GenericParameter>` without `#[serde(bound)]` overrides for the generates impls.
=> Remove unnecessary Clone bounds on Serialize impls

benches/hashmap.rs, src/nodes/hamt.rs
I was investigating replacing `rpds` with `imbl` but the iter performance was lagging behind, with this PR and (https://github.com/jneem/imbl-sized-chunks/pull/7) it's about the same.
The changes involve tidying up the control flow and avoiding recursion (sadly, it hardly ever becomes tail call optimized).
```
== before
running 1 test
test hashmap_iter_10000        ... bench:      73,539 ns/iter (+/- 3,052)
== after
running 1 test
test hashmap_iter_10000        ... bench:      53,534 ns/iter (+/- 3,011)
```
This benchmark includes https://github.com/jneem/imbl-sized-chunks/pull/7
=> Improve the performance of HashMap iterators

Cargo.toml, src/fakepool.rs, src/util.rs
Add support for using `triomphe::Arc` behind a feature flag with the same name.
[`triomphe::Arc`](https://docs.rs/triomphe/0.1.11/triomphe/struct.Arc.html) has no weak references, so it has simpler/faster copy-on-write methods like `make_mut` and `try_unwrap`.
On my x64 box the improvements are hard to detect (single digits %) but it can only get faster with contention and/or weaker memory models (e.g. arm64).
=> Add support for using `triomphe::Arc` behind a feature flag

.github/workflows/ci.yml, fuzz/Cargo.toml, fuzz/fuzz_targets/hashset.rs, fuzz/fuzz_targets/ordset.rs, fuzz/fuzz_targets/vector.rs
* Enable small nodes by default, which greatly speeds up coverage
* Utilize u32 (from u64) keys to allow generating 1.8x operations for the same fuzz input
* Update fuzz versions
* Run fuzz tests in CI for a short time
* Add fuzz OrdMap range operations (reason(s) why I stopped im in the first place)
=> Update fuzz tests and have run them in CI

src/fakepool.rs, src/hash/set.rs, src/nodes/hamt.rs, src/ord/map.rs, src/ord/set.rs
During profiling, I noticed a lot of time was being spent in memcopy. I tracked it down to less than ideal Node initialization. I ended up utilizing a combination of `UnsafeCell` and `MaybeUninit` to avoid utilizing unstable APIs.
These results are for small pairs `u64, u64` but the delta increases with larger items.
Before
```
test hashmap_insert_mut_10     ... bench:         407 ns/iter (+/- 5)
test hashmap_insert_mut_100    ... bench:       7,380 ns/iter (+/- 122)
test hashmap_insert_mut_1000   ... bench:      81,006 ns/iter (+/- 1,841)
test hashmap_insert_mut_10000  ... bench:     879,453 ns/iter (+/- 29,964)
```
After
```
test hashmap_insert_mut_10     ... bench:         353 ns/iter (+/- 7)
test hashmap_insert_mut_100    ... bench:       5,844 ns/iter (+/- 87)
test …
```
=> Speedup hashmap by speeding up node creation

src/ord/set.rs
Title is self explanatory. If possible, it would be nice to have a small bugfix release for this. The change should be fully backwards compatible.
=> feat: Make get_next/get_prev mor generic such that borrowed forms of keys can be used

src/vector/mod.rs
Self-explanatory - this PR impls `IntoIterator<Item = &mut A>` for `&mut Vector<A>` as discussed in #79.
=> Impl `IntoIterator` for `&mut Vector<A>`

src/nodes/btree.rs, src/ord/map.rs
=> Make OrdMap::range not implement ExactSizedIterator

src/ser.rs, src/tests/vector.rs, src/vector/focus.rs, src/vector/mod.rs, src/vector/rayon.rs
Also adds annotations to make running miri test easier for vector. This doesn't yet add those annotations to other places in the codebase. The `full_retain` test is needed to ensure tests cover `TreeFocusMut::get_many`.
With these changes, miri reports no UB running the non-ignored parts of the test suite.
=> Fix stacked-borrows violations in Vector

src/vector/focus.rs, src/vector/mod.rs
I noticed that these methods were more restrictive than necessary, as compared to subslicing a slice (or even Vector::slice), making it hard (though not impossible) to end up with an empty Focus. Additionally `narrow()` allowed its end index to go past `len()` which could lead to other problems.
I added some tests for these methods too.
=> Fix bounds checks on Focus::narrow and split_at

src/config.rs, src/hash/map.rs, src/hash/set.rs, src/lib.rs, src/nodes/btree.rs, src/nodes/hamt.rs, src/nodes/rrb.rs, src/ord/map.rs, src/ord/set.rs, src/util.rs, src/vector/focus.rs, src/vector/mod.rs
This cleans up a lot of warnings, by removing the unused support for specialization and memory pools.
=> Less warnings

CHANGELOG.md, src/vector/mod.rs
Manually implement `Clone` for `vector::Iter` to avoid overly strict trait bounds introduced by `#[derive(Clone)]`.
=> fix: `vector::Iter` is not `Clone` when `triomphe` is enabled

src/nodes/hamt.rs
Restore hashmap node creation optimization from #76 that got lost in the latest refactorings
Before
```
test hashmap_insert_mut_100    ... bench:       6,938.23 ns/iter (+/- 113.80)
test hashmap_insert_mut_1000   ... bench:      76,059.14 ns/iter (+/- 705.79)
test hashmap_insert_mut_10000  ... bench:     830,938.95 ns/iter (+/- 29,548.33)
```
After
```
test hashmap_insert_mut_100    ... bench:       5,872.88 ns/iter (+/- 72.71)
test hashmap_insert_mut_1000   ... bench:      63,136.52 ns/iter (+/- 577.20)
test hashmap_insert_mut_10000  ... bench:     741,631.21 ns/iter (+/- 120,330.27)
```
=> Restore hashmap node creation optimizatiom

.github/workflows/ci.yml, Cargo.toml, benches/ordmap.rs, fuzz/fuzz_targets/ordset.rs, proptest-regressions/ord/map.txt, proptest-regressions/tests/ordset.txt, src/config.rs, src/nodes/btree.rs, src/ord/map.rs, src/ord/set.rs, src/ser.rs
Rewrite OrdMap as a B+Tree for better performance and readability, as the BTree has more intricate semantics that get in the way of optimal performance. All the existing tests and APIs are kept, so it's theoretically a non-breaking change.
Performance is significantly better in most cases, with only a few small regressions. Such regressions are likely only visible in benchmarks, as the data structure is fully in the processor caches. In fact, real-world (cold cache) performance will likely be better with the new implementation as the branch keys are more tightly packed in memory. Thus, fewer cache misses are required to hit the leaves where most items are held due to the large branch factor.
A theoretical drawback of the new implementation is that there are some extra Key instances in the …
=> Rewrite OrdMap as a B+Tree for better performance and readability

src/vector/mod.rs
This pr removes the where bound `A: Ord` for the `Vector::insert_ord_by()` function as it is
unnecessary, and the purpose of the function is to make an ordered insert for a `Vector` where the
elements doesn't implement `Ord`. Please add this change to the changelog if you feel it is
necessary.
=> Don't require `A: Ord` for `Vector::insert_ord_by()`.

src/hash/map.rs, src/ord/map.rs
Similar to the existing `get_key_value` functions but return `(&K, &mut V)` instead.
=> Add `get_key_value_mut` function to maps

src/nodes/btree.rs, src/ord/map.rs
without this, rustc will infer the returned lifetime `'_` to depend on the lifetime of the key used for lookup `&BK` even though it *actually* only depends on the lifetime of self
=> fix lifetimes for ordmap

src/nodes/btree.rs, src/ord/map.rs
Reverts jneem/imbl#119 because it was a no-op and the original version of the code was easier to read.
If you run clippy on the current codebase, I would expect it to also point this out.
=> Revert "fix lifetimes for ordmap"

src/lib.rs, src/ord/map.rs, src/proptest.rs, src/shared_ptr.rs, src/vector/focus.rs, src/vector/mod.rs, src/vector/rayon.rs
Fix broken link introduced by PR #90. Also rewrite Thread Safety section because `imbl` now support it using `shared_ptr::RcK`. Might need a review on the Thread Safety rewrite since my English isn't that great.
=> docs: fix broken links and rewrite the Thread Safety section

CHANGELOG.md, src/config.rs, src/hash/map.rs, src/nodes/hamt.rs
This PR introduces two significant optimizations to the HAMT implementation, targeting the large memory overhead (e.g., a node with 32 entry capacity has as few as two values). Classic HAMT implementations in GC languages (e.g. Clojure and Scala) have an easier time implementing dynamically sized dense nodes, but that's hard to do _efficiently_ in Rust. So I tried something different in this PR.
- Linear probing: Nodes will not immediately create a new node on the next level for collision resolution. If the load factor is small enough (<= 50%), store collisions inline using linear probing. This reduces tree depth and improves cache locality.
- Small nodes: Introduce half-width nodes (16 slots vs 32) to lower memory overhead for nodes with few entries. These also use linear probing and may …
=> Optimize HAMT HashMap with linear probing and small nodes

.github/workflows/ci.yml, src/nodes/btree.rs
As of https://github.com/rust-lang/rust/pull/128254 stdlib binary search is heavily optimized for integers but is not optimal when more complex comparison functions are used.
This PR adds a custom binary search implementation that performs the minimal/optimal number of comparisons (std doesn't) and also may early return on equality matches. To prevent regressions, the code delegates to stdlib for simple to compare types.
Using Arc\<String\> keyed maps
Successful Lookups (lookup)
| Size | stdlib-only (ns) | full-custom (ns) | Improvement |
|------|------------------|------------------|-------------|
| 100 | 6,914.78 | 3,250.84 | **-52.99%** (2.13x faster) |
| 1,000 | 136,864.94 | 70,691.21 | **-48.35%** (1.94x faster) |
| 10,000 | 2,551,756.59 | 1,384,791.19 | **-45.73%** (1.84x faster) | …
=> Use optimized binary search for non-trivial types in B+Tree

benches/ordmap.rs, src/config.rs
This PR aims to lower the BTree node size from 64 to 16 to significantly speed up immutable operations. There are many tradeoffs to this, so there are a number of data points below.
16 seems to be the best option for a default, assuming bulk mutable ops on map<int, int> are rare. 32 could also be considered a good default that is not too bad in any benchmark.
Note: All benchmarks below were conducted with #143 
Lookup
| Size | node16 (ns) | node24 (ns) | node32 (ns) | node64 (ns) |
|------|-------------|-------------|-------------|-------------|
| 1,000 | 16,893.98 | 17,549.98 (+3.88%) | 14,938.43 (-11.58%) | 12,885.78 (-23.73%) |
| 10,000 | 266,911.55 | 265,269.35 (-0.62%) | 237,677.90 (-10.95%) | 214,610.08 (-19.60%) |
| 100,000 | 4,194,661.15 | 4,314,662.85 (+2.86%) | 3,843,491.42 …
=> Adjust B-tree node size to optimize for immutable operations
